/*
 * HSEVENSEG_config.c
 *
 * Created: 1/5/2025 11:18:22 AM
 *  Author: yasmeen
 */ 

#include "HSEVENSEG_config.h"

 HSEVENSEG_strSWITCHCONFG_t HSEVENSEG_enuArrHEVENSEGCongf[Num_of_SEVENSEG] =
{
	[SEVENSEG1] = {
		.LED1_Port = HSEVENSEG_enuPORTA,
		.LED1_Pin = HSEVENSEG_enuPIN1,
		.LED2_Port = HSEVENSEG_enuPORTA,
		.LED2_Pin = HSEVENSEG_enuPIN2,
		.LED3_Port = HSEVENSEG_enuPORTA,
		.LED3_Pin = HSEVENSEG_enuPIN3,
		.LED4_Port = HSEVENSEG_enuPORTA,
		.LED4_Pin = HSEVENSEG_enuPIN4,
		.LED5_Port = HSEVENSEG_enuPORTA,
		.LED5_Pin = HSEVENSEG_enuPIN5,
		.LED6_Port = HSEVENSEG_enuPORTA,
		.LED6_Pin = HSEVENSEG_enuPIN6,
		.LED7_Port = HSEVENSEG_enuPORTA,
		.LED7_Pin = HSEVENSEG_enuPIN7,
		.DOT_Port = HSEVENSEG_enuPORTA,
		.DOT_Pin = HSEVENSEG_enuPIN0,
		.CONN_Port = HSEVENSEG_enuPORTC,
		.CONN_Pin = HSEVENSEG_enuPIN0,

		.CONNECTION = HSEVENSEG_enuSEVENSEG_CC
	},
	[SEVENSEG2] = {
		.LED1_Port = HSEVENSEG_enuPORTB,
		.LED1_Pin = HSEVENSEG_enuPIN1,
		.LED2_Port = HSEVENSEG_enuPORTB,
		.LED2_Pin = HSEVENSEG_enuPIN2,
		.LED3_Port = HSEVENSEG_enuPORTB,
		.LED3_Pin = HSEVENSEG_enuPIN3,
		.LED4_Port = HSEVENSEG_enuPORTB,
		.LED4_Pin = HSEVENSEG_enuPIN4,
		.LED5_Port = HSEVENSEG_enuPORTB,
		.LED5_Pin = HSEVENSEG_enuPIN5,
		.LED6_Port = HSEVENSEG_enuPORTB,
		.LED6_Pin = HSEVENSEG_enuPIN6,
		.LED7_Port = HSEVENSEG_enuPORTB,
		.LED7_Pin = HSEVENSEG_enuPIN7,
		.DOT_Port = HSEVENSEG_enuPORTB,
		.DOT_Pin = HSEVENSEG_enuPIN0,
		.CONN_Port = HSEVENSEG_enuPORTC,
		.CONN_Pin = HSEVENSEG_enuPIN1,

		.CONNECTION = HSEVENSEG_enuSEVENSEG_CC
	}
};